version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ecom_postgres
    environment:
      POSTGRES_DB: ecom_analytics
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics_pw
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
